name: Laravel & Vue 3 CI/CD

on:
  push:
    branches: ["main"] # Trigger workflow pada push ke branch main tambahkan [deploy] pada pesan untuk menjalankan workflow

jobs:
  laravel-vue-deploy:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      # Setup PHP
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3"

      - name: 🧶 Install PHP Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate .env from example
        run: |
          cp .env.example .env
          sed -i "s|APP_URL=.*|APP_URL=https://pkkm.saicponorogo.com|" .env
          sed -i "s|DB_DATABASE=.*|DB_DATABASE=${{ secrets.DATABASE_NAME }}|" .env
          sed -i "s|DB_USERNAME=.*|DB_USERNAME=${{ secrets.DATABASE_NAME }}|" .env
          sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DATABASE_PASS }}|" .env
          sed -i "s|APP_ENV=.*|APP_ENV=production|" .env
          sed -i "s|APP_DEBUG=.*|APP_DEBUG=false|" .env
          sed -i "s|DB_CONNECTION=.*|DB_CONNECTION=mysql|" .env

      - name: 🔧 Generate Ziggy Routes
        run: php artisan ziggy:generate resources/js/ziggy.js

      - name: 🔧 Generate Key Laravel
        run: php artisan key:generate

      # Set directory permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "22" # Sesuaikan dengan versi Node.js yang digunakan proyek Anda

      # Install dependencies Vue
      - name: Install Node.js dependencies
        run: npm install

      # Build aplikasi Vue 3
      - name: Build Vue 3 app
        run: npm run build

      # Deploy public files
      - name: Siapkan file Publik untuk deploy (tanpa index.php dan .htaccess)
        run: |
          mkdir .deploy_publik
          shopt -s extglob
          cp -r public/!(index.php|.htaccess) .deploy_publik/

      - name: Siapkan file Private untuk deploy (tanpa index.php dan .htaccess)
        run: |
          mkdir .deploy_private
          rsync -av --exclude='index.php' --exclude='.htaccess' ./ .deploy_private/

      - name: Sync files to server via rsync public files
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avzr
          path: ".deploy_publik/"
          remote_path: "/home/${{ secrets.HOSTINGER_SSH_USER }}/domains/saicponorogo.com/public_html/subdomain/pkkm"
          remote_host: ${{ secrets.HOSTINGER_SSH_HOST }}
          remote_port: 65002
          remote_user: ${{ secrets.HOSTINGER_SSH_USER }}
          remote_key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Sync files to server via rsync server files
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avzr
          path: ".deploy_private/"
          remote_path: "/home/${{ secrets.HOSTINGER_SSH_USER }}/domains/saicponorogo.com/pkkm"
          remote_host: ${{ secrets.HOSTINGER_SSH_HOST }}
          remote_port: 65002
          remote_user: ${{ secrets.HOSTINGER_SSH_USER }}
          remote_key: ${{ secrets.HOSTINGER_SSH_KEY }}
